name: ugdlayout2
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  fluttertoast: ^8.2.2
  sensors: ^2.0.3
  screen_brightness: ^0.2.2
  wakelock: ^0.6.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite: ^2.2.6
  flutter_slidable: ^0.6.0

flutter:
  uses-material-design: true
  assets:
    - image/
