name: ugdlayout2
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  barcode_widget: ^2.0.4
  camera: ^0.10.5+2
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_map: ^6.0.1
  fluttertoast: ^8.2.2
  geolocator: ^10.1.0
  image_picker: ^0.8.6
  intl: ^0.17.0
  latlong2: ^0.9.0
  lottie: ^2.7.0
  pdf: ^3.10.6
  printing: ^5.11.1
  provider: ^6.0.5
  responsive_sizer: ^3.2.0
  screen_brightness: ^0.2.2
  sensors: ^2.0.3
  shared_preferences: ^2.2.1
  uuid: ^4.2.1
  wakelock: ^0.6.1
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^0.6.0
  flutter_test:
    sdk: flutter
  mobile_scanner: ^3.2.0
  sqflite: ^2.2.6

flutter:
  uses-material-design: true
  assets:
    - image/
    - assets/cancel.json
    - assets/success.json
